plugins { id 'com.android.application' }

android {
    namespace 'com.namma.metrotracker'
    compileSdk 36

    defaultConfig {
        applicationId 'com.namma.metrotracker'
        minSdk 24
        targetSdk 36
        versionCode 85
        versionName '8.5.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
