-- Namma Metro Tracker v7 database schema.
-- Run this in Supabase SQL Editor before deploying the backend.
CREATE TABLE IF NOT EXISTS metro_config (
    id integer PRIMARY KEY CHECK (id = 1),
    version integer NOT NULL,
    updated_at text NOT NULL,
    payload jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS metro_config_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version integer NOT NULL,
    updated_at text NOT NULL,
    payload jsonb NOT NULL,
    changed_by text NOT NULL DEFAULT 'system'
);
